modLoader="javafml"
loaderVersion="[43,)"
license="Maker's Mods License"
[[mods]]
modId="waxed"
displayName="Waxed"
version="0.6a-Forge-1.20.1"
logoFile="waxed_logo.png"
authors="Im_Maker"
credits=""
description='''
Adds wax blocks, wax pillars and now you can wax/unwax some blocks like copper!
Twitter/X:I_AmMaker
'''

[[dependencies.waxed]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.waxed]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.waxed]]
modId="moonlight"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="supplementaries"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="supplementaries_squared"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="quark"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="buzzy_bees"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="copperative"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="iwannaskate"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="aromatic"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="mynethersdelight"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.waxed]]
modId="twigs"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"